name: Docker Build and Push

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build docker image
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/drone-meds:latest \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/drone-meds:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/drone-meds:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/drone-meds:${{ github.sha }}